### ISSUE TITLE
Having a hard time installing and setting up on Pop OS Linux

### ISSUE THREAD

**Issue by Kamoedesu** [fosspill/FFXIV_Modding_Tool#231] opened 2021-02-09 00:35 UTC
I've been able to make it as far as the last step of manual install, I can get the list of commands to open up in Terminal with `./ffmt` but trying to use any of the commands to continue with the setup simply gives me `command 'ffmt' not found`.

Bear in mind I'm a very new Linux user, barely a few days into it at this point and I have very little knowledge of anything so far, so I wouldn't be offended by being told I did something wrong.

**Comment by lillelilje** [comment] 2021-02-09 07:34
Try to run `chmod +x ffmt` in the folder which contains the ffmt executable and run `./ffmt help` afterwards.

**Comment by Kamoedesu** [comment] 2021-02-09 14:21
EDIT: I got it, I wasn't being specific enough. I'll leave this open in case I have any additional issues, but I think I might have the hang of it by now.

**Comment by Kamoedesu** [comment] 2021-02-09 15:38
I've got it up and running, most of my mods are functional except for one, I'm getting an error 

```
ERROR: There was an error importing a modpack.
Message: The given key 'mdl' was not present in the dictionary.
```

Is that just a limitation of the tool, or is that something I can fix?

**Comment by lillelilje** [comment] 2021-02-09 16:58
@shinnova was just able to reproduce the issue independently! She's been troubleshooting for a while already.

It would be super helpful if you could mention which mod it is, and if it is something you'd rather not write here please send me an email or tell me how you'd prefer to be in touch about it!

<details> 
  <summary>@shinnova managed to make the issue happen with this mod.</summary>
   "NudaTheQueen" 
</details>

**Comment by Kamoedesu** [comment] 2021-02-09 17:30
I don't mind, it's sfw and it's ["Naty's Mani-Pedi Mega Pack"](https://www.xivmodarchive.com/modid/461). So far I haven't encountered issues with any of my other ttmp files besides this particular one, so my overall experience in XIV on Linux has been a resounding success thanks to people like you and everyone else who's made this tool work as well as it does.

If you use Discord and you'd prefer to talk there for faster response times, let me know and I'll give you my ID.

**Comment by shinnova** [comment] 2021-02-09 18:00
I think I managed to find the root cause of the issue and have fixed it. I can't reproduce the error on my end anymore, but if you don't mind, could you test [this build](https://github.com/fosspill/FFXIV_Modding_Tool/files/5953268/FFXIV_Modding_Tool-linux-0.9.8-test.zip) for me and let me know if it works for you too?

**Comment by Kamoedesu** [comment] 2021-02-09 18:04
I can, I just need to know some things since I'm still very new to this. Do I need to back anything up, and how do I go about setting up this new build, is it a simple "extract and it works" or do I need to refer back to the setup guide again as if I was doing this again from the start?

**Comment by shinnova** [comment] 2021-02-09 18:09
It's a simple extract and it works. You can even overwrite your previous files, it won't hurt anything. ^^

**Comment by Kamoedesu** [comment] 2021-02-09 18:16
Excellent, it all worked perfectly! The mod works now, and that concludes my full mod backup on my new OS. Thank you so much for the help, and I'm glad I was able to be of some menial assistance myself.

**Comment by lillelilje** [comment] 2021-02-09 18:29
No, thank *you* for making FFMT just a slight bit better!

A full new release will soon be out with a couple of other small fixes as well. Closing the issue, but make as many as you want and ask all the questions you need. Going from (presumably) Windows to Linux and then using command-line tools is not a small step :)

**Closed as completed by lillelilje** 2021-02-09 18:29 UTC
