### ISSUE TITLE
Mods Refresh is broken, reports success but does not make any changes (Linux)

### ISSUE THREAD

**Issue by taylor85345** [fosspill/FFXIV_Modding_Tool#170] opened 2020-07-25 02:36 UTC
Running the "ffmt mods refresh" command after altering modlist.cfg instantly reports success with the correct number of mods to be enabled and disabled, but no actual changes are made to game files. This makes it impossible to selectively disable mods

I am running Manjaro Linux with the Steam version of FFXIV running in Proton. I am new to ffmt and not a developer by any stretch, so if there are any logs or additional information I can provide I will be glad to do so.

**Comment by lillelilje** [comment] 2020-07-25 09:16
Looking into this today

**Comment by shinnova** [comment] 2020-07-25 13:25
As it turns out the toggling of mods is now an asynchronous task in the framework and just had to be awaited in ffmt for "ffmt mods refresh" to work as intended once more. This will be fixed in the next release.

**Closed as completed** 2020-07-25 14:22 UTC

**Comment by shinnova** [comment] 2020-07-25 16:07
@taylor85345 Could you confirm that mods refresh works with the latest release?

**Comment by taylor85345** [comment] 2020-07-29 08:33
Thank you, and sorry for the delayed response. The Mods Refresh function now behaves as expected in the new AUR build of 0.9.2 (Also much appreciated).

**Comment by lillelilje** [comment] 2020-07-29 11:05
Thank you @taylor85345! 

In case anyone else has issues, try using the shorthand "mr" instead of "mods refresh". That part will be reworked for next release anyways.
